### ISSUE TITLE
No good initial image pair found problem

### ISSUE THREAD

**Issue by Yzhbuaa** [petrhruby97/TBSfM#1]
Hello, thanks for your great work ! I used the amazing pipeline on the provided 'ship' dataset and the result is fairly good. But when I provided my own dataset and followed your instruction, the reconstruction always failed at initialization stage. Could you please give me some advice on image data acquisition. Thank you !

**Comment by petrhruby97** [comment]
Hello. Thanks for your interest in my work. COLMAP usually reports this error if the depicted scene does not have enough point correspondences. I assume that if you use a background with more point features, you may be able to reconstruct the scene better. However, it would help me if I could see how your data looks like in order to give you a more precise advice.

**Comment by Yzhbuaa** [comment]
Thank you for your advice! It seems like a bug related to path string operations. The path of images is not consistent. I will post a PR once I checked that it's not a fault caused by my carelessness.  I've tested on my dataset and the result seems good : )
